In [119]:
from nba_api.stats.static import players
import pandas as pd

from nba_api.stats.library.parameters import SeasonAll

player_dict = players.get_players()
nba_players = pd.DataFrame.from_dict(player_dict)

# Use ternary operator or write function 
# Names are case sensitive

# find team Ids
from nba_api.stats.static import teams 
teams = teams.get_teams()
nba_teams = pd.DataFrame.from_dict(teams)

In [64]:
nba_players

           id            full_name first_name     last_name  is_active
0       76001       Alaa Abdelnaby       Alaa     Abdelnaby      False
1       76002      Zaid Abdul-Aziz       Zaid    Abdul-Aziz      False
2       76003  Kareem Abdul-Jabbar     Kareem  Abdul-Jabbar      False
3          51   Mahmoud Abdul-Rauf    Mahmoud    Abdul-Rauf      False
4        1505    Tariq Abdul-Wahad      Tariq   Abdul-Wahad      False
...       ...                  ...        ...           ...        ...
4496  1627790           Ante Zizic       Ante         Zizic       True
4497    78647             Jim Zoet        Jim          Zoet      False
4498    78648            Bill Zopf       Bill          Zopf      False
4499  1627826          Ivica Zubac      Ivica         Zubac       True
4500    78650           Matt Zunic       Matt         Zunic      False

[4501 rows x 5 columns]

In [65]:
players.find_players_by_first_name('kobe')

[{'id': 977,
  'full_name': 'Kobe Bryant',
  'first_name': 'Kobe',
  'last_name': 'Bryant',
  'is_active': False}]

In [19]:
active = nba_players[nba_players['is_active'] == True]

In [6]:
nba_teams

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Atlanta,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966
5,1610612742,Dallas Mavericks,DAL,Mavericks,Dallas,Texas,1980
6,1610612743,Denver Nuggets,DEN,Nuggets,Denver,Colorado,1976
7,1610612744,Golden State Warriors,GSW,Warriors,Golden State,California,1946
8,1610612745,Houston Rockets,HOU,Rockets,Houston,Texas,1967
9,1610612746,Los Angeles Clippers,LAC,Clippers,Los Angeles,California,1970
10,1610612747,Los Angeles Lakers,LAL,Lakers,Los Angeles,California,1948
11,1610612748,Miami Heat,MIA,Heat,Miami,Florida,1988
12,1610612749,Milwaukee Bucks,MIL,Bucks,Milwaukee,Wisconsin,1968
13,1610612750,Minnesota Timberwolves,MIN,Timberwolves,Minnesota,Minnesota,1989
14,1610612751,Brooklyn Nets,BKN,Nets,Brooklyn,New York,1976
15,1610612752,New York Knicks,NYK,Knicks,New York,New York,1946
16,1610612753,Orlando Magic,ORL,Magic,Orlando,Florida,1989
17,1610612754,Indiana Pacers,IND,Pacers,Indiana,Indiana,1976
18,1610612755,Philadelphia 76ers,PHI,76ers,Philadelphia,Pennsylvania,1949
19,1610612756,Phoenix Suns,PHX,Suns,Phoenix,Arizona,1968
20,1610612757,Portland Trail Blazers,POR,Trail Blazers,Portland,Oregon,1970
21,1610612758,Sacramento Kings,SAC,Kings,Sacramento,California,1948
22,1610612759,San Antonio Spurs,SAS,Spurs,San Antonio,Texas,1976
23,1610612760,Oklahoma City Thunder,OKC,Thunder,Oklahoma City,Oklahoma,1967
24,1610612761,Toronto Raptors,TOR,Raptors,Toronto,Ontario,1995
25,1610612762,Utah Jazz,UTA,Jazz,Utah,Utah,1974
26,1610612763,Memphis Grizzlies,MEM,Grizzlies,Memphis,Tennessee,1995
27,1610612764,Washington Wizards,WAS,Wizards,Washington,District of Columbia,1961
28,1610612765,Detroit Pistons,DET,Pistons,Detroit,Michigan,1948
29,1610612766,Charlotte Hornets,CHA,Hornets,Charlotte,North Carolina,1988

In [29]:
from nba_api.stats.endpoints import leaguedashplayerclutch as clutch

In [176]:
clutch_df = clutch.LeagueDashPlayerClutch(season = '2018-21').get_data_frames()

In [177]:
clutch_df[0]

Empty DataFrame
Columns: [GROUP_SET, PLAYER_ID, PLAYER_NAME, TEAM_ID, TEAM_ABBREVIATION, AGE, GP, W, L, W_PCT, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, TOV, STL, BLK, BLKA, PF, PFD, PTS, PLUS_MINUS, NBA_FANTASY_PTS, DD2, TD3, GP_RANK, W_RANK, L_RANK, W_PCT_RANK, MIN_RANK, FGM_RANK, FGA_RANK, FG_PCT_RANK, FG3M_RANK, FG3A_RANK, FG3_PCT_RANK, FTM_RANK, FTA_RANK, FT_PCT_RANK, OREB_RANK, DREB_RANK, REB_RANK, AST_RANK, TOV_RANK, STL_RANK, BLK_RANK, BLKA_RANK, PF_RANK, PFD_RANK, PTS_RANK, PLUS_MINUS_RANK, NBA_FANTASY_PTS_RANK, DD2_RANK, TD3_RANK, CFID, CFPARAMS]
Index: []

[0 rows x 66 columns]

In [18]:
clutch_rankings = pd.DataFrame(LBJ_clutch.get_data_frames()[0])

In [223]:
from nba_api.stats.endpoints import playergamelog
from nba_api.stats.endpoints import playergamelogs

#Call the API endpoint passing in lebron's ID & which season 
gamelog_bron = playergamelog.PlayerGameLog(player_id='2544', season = '2018')

#Converts gamelog object into a pandas dataframe
#can also convert to JSON or dictionary  
df_bron_games_2018 = gamelog_bron.get_data_frames()

# If you want all seasons, you must import the SeasonAll parameter 


gamelog_bron_all = playergamelog.PlayerGameLog(player_id='2544', season = SeasonAll.all)

df_bron_games_all = gamelog_bron_all.get_data_frames()[0]

type(gamelog_bron_all)

nba_api.stats.endpoints.playergamelog.PlayerGameLog

In [253]:
gamelog_bron_all = playergamelog.PlayerGameLog(player_id='2544', season = )

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [268]:
gamelog_bron_all.get_data_frames()[0]

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22020,2544,0022001072,"MAY 16, 2021",LAL @ NOP,W,27,11,22,0.500,...,0,1,6,3,0,2,0,25,-2,1
1,22020,2544,0022001061,"MAY 15, 2021",LAL @ IND,W,28,11,22,0.500,...,4,7,8,0,0,4,2,24,7,1
2,22020,2544,0022000974,"MAY 02, 2021",LAL vs. TOR,L,28,6,11,0.545,...,7,7,6,0,0,5,2,19,-4,1
3,22020,2544,0022000956,"APR 30, 2021",LAL vs. SAC,L,32,6,12,0.500,...,7,8,7,2,1,5,1,16,5,1
4,22020,2544,0022000640,"MAR 20, 2021",LAL vs. ATL,L,11,3,6,0.500,...,1,1,4,0,0,1,0,10,-5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,22003,2544,0020300068,"NOV 07, 2003",CLE @ IND,L,44,8,18,0.444,...,5,5,3,0,0,7,2,23,-7,0
1306,22003,2544,0020300057,"NOV 05, 2003",CLE vs. DEN,L,41,3,11,0.273,...,9,11,7,2,3,2,1,7,-3,0
1307,22003,2544,0020300038,"NOV 01, 2003",CLE @ POR,L,39,3,12,0.250,...,4,4,6,2,0,2,3,8,-21,0
1308,22003,2544,0020300018,"OCT 30, 2003",CLE @ PHX,L,41,8,17,0.471,...,10,12,8,1,0,7,1,21,-3,0
1309,22003,2544,0020300014,"OCT 29, 2003",CLE @ SAC,L,42,12,20,0.600,...,4,6,9,4,0,2,3,25,-9,0

AttributeError: 'PlayerGameLog' object has no attribute 'columns'

In [263]:
gamelogs_bron_all = playergamelogs.PlayerGameLogs(player_id_nullable='2544', season_nullable = '2016-18')

In [252]:
from nba_api.stats.library.parameters import SeasonAll_Time

SeasonAll_Time.all_time

'All Time'

In [265]:
gamelogs_bron_all.get_data_frames()[0]

Empty DataFrame
Columns: [SEASON_YEAR, PLAYER_ID, PLAYER_NAME, TEAM_ID, TEAM_ABBREVIATION, TEAM_NAME, GAME_ID, GAME_DATE, MATCHUP, WL, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, TOV, STL, BLK, BLKA, PF, PFD, PTS, PLUS_MINUS, NBA_FANTASY_PTS, DD2, TD3, GP_RANK, W_RANK, L_RANK, W_PCT_RANK, MIN_RANK, FGM_RANK, FGA_RANK, FG_PCT_RANK, FG3M_RANK, FG3A_RANK, FG3_PCT_RANK, FTM_RANK, FTA_RANK, FT_PCT_RANK, OREB_RANK, DREB_RANK, REB_RANK, AST_RANK, TOV_RANK, STL_RANK, BLK_RANK, BLKA_RANK, PF_RANK, PFD_RANK, PTS_RANK, PLUS_MINUS_RANK, NBA_FANTASY_PTS_RANK, DD2_RANK, TD3_RANK]
Index: []

[0 rows x 64 columns]

In [192]:
gamelog_bron.get_data_frames()[0]

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22018,2544,0021801135,"MAR 29, 2019",LAL vs. CHA,W,32,11,19,0.579,...,3,3,9,0,0,6,1,27,14,1
1,22018,2544,0021801116,"MAR 26, 2019",LAL vs. WAS,W,34,11,20,0.550,...,7,7,14,1,0,3,1,23,3,1
2,22018,2544,0021801102,"MAR 24, 2019",LAL vs. SAC,W,35,9,22,0.409,...,9,11,11,2,1,4,1,29,5,1
3,22018,2544,0021801086,"MAR 22, 2019",LAL vs. BKN,L,37,8,25,0.320,...,6,9,14,1,1,8,3,25,-2,1
4,22018,2544,0021801042,"MAR 17, 2019",LAL @ NYK,L,35,11,26,0.423,...,4,6,8,0,1,2,2,33,9,2
5,22018,2544,0021801023,"MAR 14, 2019",LAL @ TOR,L,32,12,23,0.522,...,4,4,6,1,0,4,2,29,0,1
6,22018,2544,0021801009,"MAR 12, 2019",LAL @ CHI,W,33,15,23,0.652,...,9,10,4,2,0,5,2,36,9,1
7,22018,2544,0021800989,"MAR 09, 2019",LAL vs. BOS,L,28,13,23,0.565,...,8,10,12,0,0,3,0,30,11,1
8,22018,2544,0021800974,"MAR 06, 2019",LAL vs. DEN,L,31,13,22,0.591,...,7,7,7,1,1,4,4,31,-8,1
9,22018,2544,0021800958,"MAR 04, 2019",LAL vs. LAC,L,42,9,18,0.500,...,8,8,6,1,1,2,3,27,-11,1
10,22018,2544,0021800942,"MAR 02, 2019",LAL @ PHX,L,41,10,21,0.476,...,9,9,16,0,0,3,2,27,-1,1
11,22018,2544,0021800934,"MAR 01, 2019",LAL vs. MIL,L,39,10,19,0.526,...,5,7,10,1,0,3,2,31,-4,1
12,22018,2544,0021800921,"FEB 27, 2019",LAL vs. NOP,W,37,13,24,0.542,...,5,6,10,2,1,2,2,33,2,1
13,22018,2544,0021800904,"FEB 25, 2019",LAL @ MEM,L,40,8,23,0.348,...,9,12,11,3,0,5,3,24,2,1
14,22018,2544,0021800887,"FEB 23, 2019",LAL @ NOP,L,39,11,17,0.647,...,7,7,12,4,1,4,0,27,-10,1
15,22018,2544,0021800872,"FEB 21, 2019",LAL vs. HOU,W,40,11,23,0.478,...,8,12,6,1,1,4,1,29,6,1
16,22018,2544,0021800848,"FEB 12, 2019",LAL @ ATL,L,43,8,20,0.400,...,9,11,16,3,1,2,3,28,0,1
17,22018,2544,0021800835,"FEB 10, 2019",LAL @ PHI,L,33,8,16,0.500,...,10,10,9,0,0,4,3,18,0,1
18,22018,2544,0021800814,"FEB 07, 2019",LAL @ BOS,W,38,11,21,0.524,...,10,12,12,3,0,3,4,28,11,1
19,22018,2544,0021800798,"FEB 05, 2019",LAL @ IND,L,30,7,12,0.583,...,7,7,9,1,0,6,1,18,-17,1
20,22018,2544,0021800769,"JAN 31, 2019",LAL @ LAC,W,40,9,22,0.409,...,13,14,9,1,0,4,0,24,2,1
21,22018,2544,0021800500,"DEC 25, 2018",LAL @ GSW,W,21,6,11,0.545,...,11,13,5,1,0,2,1,17,5,1
22,22018,2544,0021800496,"DEC 23, 2018",LAL vs. MEM,L,36,8,14,0.571,...,13,14,7,1,1,4,0,22,-3,1
23,22018,2544,0021800478,"DEC 21, 2018",LAL vs. NOP,W,39,8,20,0.400,...,10,12,14,2,0,2,3,22,13,1
24,22018,2544,0021800453,"DEC 18, 2018",LAL @ BKN,L,41,13,23,0.565,...,12,13,8,1,1,5,1,36,4,1
25,22018,2544,0021800439,"DEC 16, 2018",LAL @ WAS,L,32,5,16,0.313,...,6,6,3,0,1,4,0,13,-21,1
26,22018,2544,0021800430,"DEC 15, 2018",LAL @ CHA,W,30,7,15,0.467,...,11,12,11,1,0,3,0,24,31,1
27,22018,2544,0021800416,"DEC 13, 2018",LAL @ HOU,L,36,12,18,0.667,...,5,5,4,2,0,3,1,29,-9,1
28,22018,2544,0021800401,"DEC 10, 2018",LAL vs. MIA,W,38,10,19,0.526,...,9,9,12,1,0,2,0,28,18,1
29,22018,2544,0021800384,"DEC 08, 2018",LAL @ MEM,W,32,9,18,0.500,...,7,8,9,2,0,5,2,20,21,1
30,22018,2544,0021800375,"DEC 07, 2018",LAL @ SAS,L,37,13,28,0.464,...,6,8,11,2,0,1,4,35,-19,1
31,22018,2544,0021800364,"DEC 05, 2018",LAL vs. SAS,W,40,15,24,0.625,...,5,5,6,2,0,2,1,42,19,1
32,22018,2544,0021800337,"DEC 02, 2018",LAL vs. PHX,W,31,9,17,0.529,...,6,6,8,0,1,5,0,22,12,1
33,22018,2544,0021800328,"NOV 30, 2018",LAL vs. DAL,W,31,12,21,0.571,...,3,5,4,0,1,4,3,28,10,1
34,22018,2544,0021800317,"NOV 29, 2018",LAL vs. IND,W,38,15,27,0.556,...,8,9,7,2,0,4,2,38,19,1
35,22018,2544,0021800304,"NOV 27, 2018",LAL @ DEN,L,30,5,15,0.333,...,7,7,2,2,2,4,0,14,-23,1
36,22018,2544,0021800286,"NOV 25, 2018",LAL vs. ORL,L,40,8,14,0.571,...,4,4,7,0,1,6,4,24,-14,1
37,22018,2544,0021800278,"NOV 23, 2018",LAL vs. UTA,W,35,8,17,0.471,...,9,10,7,2,1,5,1,22,13,1
38,22018,2544,0021800256,"NOV 21, 2018",LAL @ CLE,W,36,11,20,0.550,...,12,14,7,0,1,4,3,32,9,1
39,22018,2544,0021800235,"NOV 18, 2018",LAL @ MIA,W,38,19,31,0.613,...,7,8,3,2,1,2,3,51,20,1
40,22018,2544,0021800227,"NOV 17, 2018",LAL @ ORL,L,26,8,19,0.421,...,4,4,7,0,1,3,0,22,-11,1
41,22018,2544,0021800212,"NOV 14, 2018",LAL vs. POR,W,36,13,19,0.684,...,8,10,9,1,3,4,0,44,4,1
42,22018,2544,0021800189,"NOV 11, 2018",LAL vs. ATL,W,34,10,20,0.500,...,4,7,4,2,0,4,1,26,22,1
43,22018,2544,0021800183,"NOV 10, 2018",LAL @ SAC,W,31,10,18,0.556,...,6,7,2,1,0,3,2,25,2,1
44,22018,2544,0021800162,"NOV 07, 2018",LAL vs. MIN,W,39,10,21,0.476,...,10,11,9,0,2,3,1,24,3,1
45,22018,2544,0021800139,"NOV 04, 2018",LAL vs. TOR,L,28,6,12,0.500,...,2,2,6,0,1,3,3,18,-16,1
46,22018,2544,0021800132,"NOV 03, 2018",LAL @ POR,W,31,9,20,0.450,...,5,5,7,0,2,3,1,28,-22,1
47,22018,2544,0021800109,"OCT 31, 2018",LAL vs. DAL,W,39,11,19,0.579,...,5,5,6,3,0,3,3,29,5,1
48,22018,2544,0021800093,"OCT 29, 2018",LAL @ MIN,L,36,11,23,0.478,...,7,10,8,2,2,5,2,29,-6,1
49,22018,2544,0021800082,"OCT 27, 2018",LAL @ SAS,L,34,13,21,0.619,...,10,11,4,2,0,4,3,35,-1,1
50,22018,2544,0021800066,"OCT 25, 2018",LAL vs. DEN,W,35,10,17,0.588,...,11,11,11,3,0,2,3,28,13,1
51,22018,2544,0021800060,"OCT 24, 2018",LAL @ PHX,W,28,7,16,0.438,...,7,7,10,3,0,0,1,19,19,1
52,22018,2544,0021800048,"OCT 22, 2018",LAL vs. SAS,L,43,11,25,0.440,...,6,8,14,1,1,5,2,32,-5,1
53,22018,2544,0021800035,"OCT 20, 2018",LAL vs. HOU,L,39,9,22,0.409,...,5,5,5,2,1,1,0,24,-13,1
54,22018,2544,0021800016,"OCT 18, 2018",LAL @ POR,L,37,9,16,0.563,...,10,12,6,1,0,6,3,26,-4,1

In [156]:
df_bron_games_all.columns

Index(['SEASON_ID', 'Player_ID', 'Game_ID', 'GAME_DATE', 'MATCHUP', 'WL',
       'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA',
       'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF',
       'PTS', 'PLUS_MINUS', 'VIDEO_AVAILABLE'],
      dtype='object')

In [164]:
lebron_std = df_bron_games_all.std()

In [169]:
lebron_std

Player_ID           0.000000
MIN                 5.278835
FGM                 3.077230
FGA                 4.787529
FG_PCT              0.111228
FG3M                1.436018
FG3A                2.427038
FG3_PCT             0.246978
FTM                 3.404375
FTA                 4.159666
FT_PCT              0.203238
OREB                1.160305
DREB                2.729165
REB                 3.019838
AST                 2.993346
STL                 1.291143
BLK                 0.899824
TOV                 1.822418
PF                  1.274524
PTS                 7.787720
PLUS_MINUS         12.618389
VIDEO_AVAILABLE     0.510148
dtype: float64

In [30]:
df_bron_games_all[0].columns

Index(['SEASON_ID', 'Player_ID', 'Game_ID', 'GAME_DATE', 'MATCHUP', 'WL',
       'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA',
       'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF',
       'PTS', 'PLUS_MINUS', 'VIDEO_AVAILABLE'],
      dtype='object')

In [28]:
clutch.sort_values('GP')

,GROUP_SET,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS
226,Players,1628395,Jordan Bell,1610612744,GSW,26.0,1,1,0,1.000,...,1,1,319,368,232,371,201,20,1,"1628395,1610612744"
232,Players,1630221,Josh Hall,1610612760,OKC,20.0,1,1,0,1.000,...,1,87,260,335,143,407,139,20,1,"1630221,1610612760"
306,Players,1630210,Markus Howard,1610612743,DEN,22.0,1,0,1,0.000,...,1,87,319,368,216,414,201,20,1,"1630210,1610612743"
136,Players,1629091,Elijah Bryant,1610612749,MIL,26.0,1,0,1,0.000,...,1,1,319,368,232,414,201,20,1,"1629091,1610612749"
387,Players,1630241,Sam Merrill,1610612749,MIL,25.0,1,0,1,0.000,...,1,1,319,368,199,414,201,20,1,"1630241,1610612749"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,Players,1627759,Jaylen Brown,1610612738,BOS,24.0,36,14,22,0.389,...,403,433,27,30,439,41,33,20,1,"1627759,1610612738"
318,Players,1628969,Mikal Bridges,1610612756,PHX,24.0,36,24,12,0.667,...,265,338,60,34,43,27,101,20,1,"1628969,1610612756"
218,Players,203925,Joe Harris,1610612751,BKN,29.0,37,25,12,0.676,...,367,413,188,95,20,91,201,20,1,"203925,1610612751"
210,Players,1628369,Jayson Tatum,1610612738,BOS,23.0,38,17,21,0.447,...,403,394,8,6,424,7,22,12,1,"1628369,1610612738"
44,Players,1627741,Buddy Hield,1610612758,SAC,28.0,39,21,18,0.538,...,1,453,50,42,362,36,101,20,1,"1627741,1610612758"

In [20]:
list(clutch_rankings.columns)

['GROUP_SET',
 'PLAYER_ID',
 'PLAYER_NAME',
 'TEAM_ID',
 'TEAM_ABBREVIATION',
 'AGE',
 'GP',
 'W',
 'L',
 'W_PCT',
 'MIN',
 'FGM',
 'FGA',
 'FG_PCT',
 'FG3M',
 'FG3A',
 'FG3_PCT',
 'FTM',
 'FTA',
 'FT_PCT',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'TOV',
 'STL',
 'BLK',
 'BLKA',
 'PF',
 'PFD',
 'PTS',
 'PLUS_MINUS',
 'NBA_FANTASY_PTS',
 'DD2',
 'TD3',
 'GP_RANK',
 'W_RANK',
 'L_RANK',
 'W_PCT_RANK',
 'MIN_RANK',
 'FGM_RANK',
 'FGA_RANK',
 'FG_PCT_RANK',
 'FG3M_RANK',
 'FG3A_RANK',
 'FG3_PCT_RANK',
 'FTM_RANK',
 'FTA_RANK',
 'FT_PCT_RANK',
 'OREB_RANK',
 'DREB_RANK',
 'REB_RANK',
 'AST_RANK',
 'TOV_RANK',
 'STL_RANK',
 'BLK_RANK',
 'BLKA_RANK',
 'PF_RANK',
 'PFD_RANK',
 'PTS_RANK',
 'PLUS_MINUS_RANK',
 'NBA_FANTASY_PTS_RANK',
 'DD2_RANK',
 'TD3_RANK',
 'CFID',
 'CFPARAMS']

In [26]:
clutch_rankings.sort_values('PLUS_MINUS', ascending = False)[['PLAYER_NAME','GP','PLUS_MINUS']]

           PLAYER_NAME  GP  PLUS_MINUS
77      Damian Lillard  34         100
372   Robert Covington  33          95
45         CJ McCollum  20          75
162     Gordon Hayward  20          74
170  Immanuel Quickley  23          69
..                 ...  ..         ...
166     Hamidou Diallo  10         -52
278         Kyle Lowry  23         -52
120   Domantas Sabonis  32         -65
331       Myles Turner  28         -65
18     Anthony Edwards  32         -68

[454 rows x 3 columns]

In [2]:
from nba_api.stats.endpoints import playercareerstats

Empty DataFrame
Columns: [GROUP_SET, PLAYER_ID, PLAYER_NAME, TEAM_ID, TEAM_ABBREVIATION, AGE, GP, W, L, W_PCT, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, TOV, STL, BLK, BLKA, PF, PFD, PTS, PLUS_MINUS, NBA_FANTASY_PTS, DD2, TD3, GP_RANK, W_RANK, L_RANK, W_PCT_RANK, MIN_RANK, FGM_RANK, FGA_RANK, FG_PCT_RANK, FG3M_RANK, FG3A_RANK, FG3_PCT_RANK, FTM_RANK, FTA_RANK, FT_PCT_RANK, OREB_RANK, DREB_RANK, REB_RANK, AST_RANK, TOV_RANK, STL_RANK, BLK_RANK, BLKA_RANK, PF_RANK, PFD_RANK, PTS_RANK, PLUS_MINUS_RANK, NBA_FANTASY_PTS_RANK, DD2_RANK, TD3_RANK, CFID, CFPARAMS]
Index: []

[0 rows x 66 columns]

In [32]:
from nba_api.stats.endpoints import playerdashboardbyclutch as pdc

In [78]:
clutch_df_pdc = pdc.PlayerDashboardByClutch(player_id = '2544').get_data_frames()

In [350]:
clutch_df_pdc[0]

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS
0,Overall,2020-21,45,30,15,0.667,1503.701667,422,823,0.513,...,1,1,1,1,1,1,1,1,11,2020-21

In [90]:
from nba_api.stats.endpoints import leaguedashplayerstats as playerstats

In [91]:
pstats = playerstats.LeagueDashPlayerStats()

In [99]:
p_df = pstats.get_data_frames()[0]

In [100]:
p_df

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,MIN,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS
0,203932,Aaron Gordon,1610612743,DEN,25.0,50,29,21,0.580,1383.780000,...,409,314,95,156,124,150,115,17,5,"203932,1610612743"
1,1628988,Aaron Holiday,1610612754,IND,24.0,66,30,36,0.455,1176.086667,...,432,325,201,203,218,244,178,29,5,"1628988,1610612754"
2,1630174,Aaron Nesmith,1610612738,BOS,21.0,46,22,24,0.478,668.731667,...,237,301,354,343,258,347,245,29,5,"1630174,1610612738"
3,1627846,Abdel Nader,1610612756,PHX,27.0,24,16,8,0.667,355.250000,...,149,152,328,367,162,380,245,29,5,"1627846,1610612756"
4,1629690,Adam Mokoka,1610612741,CHI,22.0,14,3,11,0.214,56.178333,...,39,34,519,500,262,510,245,29,5,"1629690,1610612741"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,1627812,Yogi Ferrell,1610612746,LAC,28.0,10,4,6,0.400,136.981667,...,136,76,421,447,235,447,245,29,5,"1627812,1610612746"
536,1629139,Yuta Watanabe,1610612761,TOR,26.0,50,24,26,0.480,722.823333,...,198,219,334,343,354,320,245,29,5,"1629139,1610612761"
537,203897,Zach LaVine,1610612741,CHI,26.0,58,26,32,0.448,2033.626667,...,526,465,32,13,266,24,115,29,5,"203897,1610612741"
538,1630192,Zeke Nnaji,1610612743,DEN,20.0,42,30,12,0.714,397.278333,...,170,135,414,380,424,396,245,29,5,"1630192,1610612743"
539,1629627,Zion Williamson,1610612740,NOP,20.0,61,29,32,0.475,2025.890000,...,540,457,6,10,107,16,33,29,5,"1629627,1610612740"

In [102]:
p_df.columns

Index(['PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'TEAM_ABBREVIATION', 'AGE', 'GP',
       'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A',
       'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV',
       'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS',
       'NBA_FANTASY_PTS', 'DD2', 'TD3', 'GP_RANK', 'W_RANK', 'L_RANK',
       'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK',
       'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK',
       'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK', 'REB_RANK', 'AST_RANK',
       'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK', 'PFD_RANK',
       'PTS_RANK', 'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK', 'DD2_RANK',
       'TD3_RANK', 'CFID', 'CFPARAMS'],
      dtype='object')

SyntaxError: invalid character in identifier (<ipython-input-103-02e6189d3650>, line 4)

In [272]:
clutch_df_min = clutch.LeagueDashPlayerClutch(per_mode_detailed = 'PerMinute', season = 'ALL').get_data_frames()[0]

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [271]:
clutch_df_min

,GROUP_SET,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS
0,Players,1627773,AJ Hammons,1610612742,DAL,24.0,2,1,1,0.500,...,200,94,6,28,354,7,177,16,1,"1627773,1610612742"
1,Players,201166,Aaron Brooks,1610612754,IND,32.0,2,0,2,0.000,...,11,235,327,296,359,390,177,16,1,"201166,1610612754"
2,Players,203932,Aaron Gordon,1610612753,ORL,21.0,30,15,15,0.500,...,84,170,193,231,345,265,71,16,1,"203932,1610612753"
3,Players,203940,Adreian Payne,1610612750,MIN,26.0,2,0,2,0.000,...,200,2,327,368,430,396,177,16,1,"203940,1610612750"
4,Players,201143,Al Horford,1610612738,BOS,31.0,43,28,15,0.651,...,117,133,248,186,108,120,41,16,1,"201143,1610612738"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,Players,201163,Wilson Chandler,1610612743,DEN,30.0,31,13,18,0.419,...,133,111,95,154,282,127,61,16,1,"201163,1610612743"
430,Players,1627812,Yogi Ferrell,1610612742,DAL,24.0,16,8,8,0.500,...,200,103,19,65,247,177,177,16,1,"1627812,1610612742"
431,Players,203897,Zach LaVine,1610612750,MIN,22.0,24,8,16,0.333,...,200,257,261,213,261,282,177,16,1,"203897,1610612750"
432,Players,2216,Zach Randolph,1610612763,MEM,35.0,33,16,17,0.485,...,61,234,138,92,222,94,18,16,1,"2216,1610612763"
433,Players,2585,Zaza Pachulia,1610612744,GSW,33.0,9,5,4,0.556,...,40,48,139,321,339,293,177,16,1,"2585,1610612744"

In [115]:
clutch_df_min[['PLAYER_NAME', 'MIN', 'REB', 'PTS' ]]

         PLAYER_NAME         MIN   REB   PTS
0       Aaron Gordon   55.225000  0.18  0.22
1      Aaron Holiday   26.756667  0.07  0.56
2      Aaron Nesmith   13.948333  0.29  0.29
3        Abdel Nader    7.970000  0.00  0.13
4         Al Horford   57.211667  0.28  0.40
..               ...         ...   ...   ...
449     Yogi Ferrell    5.383333  0.19  0.00
450    Yuta Watanabe   13.170000  0.23  0.38
451      Zach LaVine  104.576667  0.19  1.13
452       Zeke Nnaji    1.383333  0.00  0.00
453  Zion Williamson  109.893333  0.23  0.88

[454 rows x 4 columns]

In [113]:
clutch_df_min.columns

Index(['GROUP_SET', 'PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS',
       'NBA_FANTASY_PTS', 'DD2', 'TD3', 'GP_RANK', 'W_RANK', 'L_RANK',
       'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK',
       'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK',
       'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK', 'REB_RANK', 'AST_RANK',
       'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK', 'PFD_RANK',
       'PTS_RANK', 'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK', 'DD2_RANK',
       'TD3_RANK', 'CFID', 'CFPARAMS'],
      dtype='object')

In [178]:
from nba_api.stats.endpoints import leaguedashplayerstats

In [204]:
from nba_api.stats.library.parameters import SeasonAllTime

from nba_api.stats.library.parameters import SeasonAllNullable

In [206]:
SeasonAllTime.alltime

'ALLTIME'

In [216]:
import requests
import json
player_stats = leaguedashplayerstats.LeagueDashPlayerStats(season = 'ALL').get_data_frames()[0]

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [188]:
player_stats

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,MIN,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS
0,2062,A.J. Guyton,1610612741,CHI,24.0,45,10,35,0.222,603.930000,...,50,74,153,268,290,300,225,18,5,"2062,1610612741"
1,243,Aaron McKie,1610612755,PHI,29.0,48,26,22,0.542,1469.013333,...,319,155,153,157,76,173,176,18,5,"243,1610612755"
2,1425,Aaron Williams,1610612751,NJN,30.0,82,52,30,0.634,1549.918333,...,337,389,153,154,74,155,225,18,5,"1425,1610612751"
3,1502,Adonal Foyle,1610612744,GSW,27.0,79,19,60,0.241,1485.290000,...,258,331,56,221,406,143,127,18,5,"1502,1610612744"
4,1559,Adrian Griffin,1610612742,DAL,27.0,58,40,18,0.690,1386.620000,...,229,265,153,208,66,197,225,18,5,"1559,1610612742"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,1895,William Avery,1610612750,MIN,22.0,28,17,11,0.607,260.356667,...,122,59,153,357,229,363,225,18,5,"1895,1610612750"
436,2216,Zach Randolph,1610612757,POR,20.0,41,22,19,0.537,237.201667,...,154,83,153,329,229,343,225,18,5,"2216,1610612757"
437,1442,Zeljko Rebraca,1610612765,DET,30.0,74,46,28,0.622,1178.491667,...,258,360,56,176,107,184,176,18,5,"1442,1610612765"
438,1985,Zendon Hamilton,1610612743,DEN,27.0,54,17,37,0.315,846.240000,...,341,197,29,240,410,252,96,18,5,"1985,1610612743"
439,980,Zydrunas Ilgauskas,1610612739,CLE,27.0,62,23,39,0.371,1330.233333,...,323,352,29,131,346,147,87,18,5,"980,1610612739"

In [311]:
start = 1996
end = 2021


clutch_data = []
counter = 0
for start_year in range(start, end):
    season = '{}-{}'.format(start_year, str(start_year + 1)[2:])
    print(season)
    clutch_data.append(clutch.LeagueDashPlayerClutch
                  (per_mode_detailed = 'PerMinute', 
                   season = 
                   season).get_data_frames()[0][['PLAYER_ID', 'PLAYER_NAME', 'MIN', 'GP', 'W', 'L', 'PTS', 'REB', 'AST', 'FGM','FGA','FTA', 'PLUS_MINUS']])

1996-97
1997-98
1998-99
1999-00
2000-01
2001-02
2002-03
2003-04
2004-05
2005-06
2006-07
2007-08
2008-09
2009-10
2010-11
2011-12
2012-13
2013-14
2014-15
2015-16
2016-17
2017-18
2018-19
2019-20
2020-21

In [277]:
clutch_df_min_all = pd.DataFrame()

In [292]:
frames[2][['MIN', 'PLAYER_NAME', 'PTS', 'AST']]

            MIN      PLAYER_NAME   PTS   AST
1     66.863333      Aaron McKie  0.39  0.12
6     58.611667   Alan Henderson  0.24  0.03
7    109.571667    Allan Houston  0.29  0.07
8    124.431667    Allen Iverson  0.68  0.08
9     86.326667  Alonzo Mourning  0.46  0.00
..          ...              ...   ...   ...
354   59.596667        Vin Baker  0.44  0.08
355   69.266667     Vince Carter  0.77  0.07
358  125.171667      Vlade Divac  0.54  0.04
360   61.065000    Walt Williams  0.15  0.05
362   54.106667    Wesley Person  0.28  0.00

[141 rows x 4 columns]

In [290]:
frames[2].columns

Index(['GROUP_SET', 'PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS',
       'NBA_FANTASY_PTS', 'DD2', 'TD3', 'GP_RANK', 'W_RANK', 'L_RANK',
       'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK',
       'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK',
       'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK', 'REB_RANK', 'AST_RANK',
       'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK', 'PFD_RANK',
       'PTS_RANK', 'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK', 'DD2_RANK',
       'TD3_RANK', 'CFID', 'CFPARAMS'],
      dtype='object')

In [296]:
frames[0]

,GROUP_SET,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS
0,Players,1049,None,NaN,None,NaN,1,0,1,0.000,...,206,337,19,319,171,362,184,19,1,"1049,"
1,Players,2179,None,NaN,None,NaN,5,4,1,0.800,...,206,337,19,319,13,362,184,19,1,"2179,"
2,Players,93,None,NaN,None,NaN,1,1,0,1.000,...,206,337,19,319,171,362,184,19,1,"93,"
3,Players,920,A.C. Green,1.610613e+09,DAL,33.0,34,11,23,0.324,...,192,261,19,304,318,322,44,19,1,"920,1610612742"
4,Players,243,Aaron McKie,1.610613e+09,DET,24.0,25,11,14,0.440,...,206,107,19,291,244,280,129,19,1,"243,1610612765"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,Players,335,Willie Anderson,1.610613e+09,MIA,30.0,5,4,1,0.800,...,206,337,19,104,10,32,184,19,1,"335,1610612748"
392,Players,416,Willie Burton,1.610613e+09,ATL,29.0,6,5,1,0.833,...,23,27,19,292,66,341,184,19,1,"416,1610612737"
393,Players,1365,Xavier McDaniel,1.610613e+09,NJN,34.0,19,9,10,0.474,...,135,251,19,87,224,118,105,19,1,"1365,1610612751"
394,Players,212,Yinka Dare,1.610613e+09,NJN,24.0,2,1,1,0.500,...,206,14,19,319,376,362,184,19,1,"212,1610612751"
395,Players,440,Zan Tabak,1.610613e+09,TOR,27.0,3,2,1,0.667,...,206,337,19,319,171,360,184,19,1,"440,1610612761"

In [306]:
frames[1].merge(frames[0], how='outer', on = 'PLAYER_ID').columns

Index(['GROUP_SET_x', 'PLAYER_ID', 'PLAYER_NAME_x', 'TEAM_ID_x',
       'TEAM_ABBREVIATION_x', 'AGE_x', 'GP_x', 'W_x', 'L_x', 'W_PCT_x',
       ...
       'BLKA_RANK_y', 'PF_RANK_y', 'PFD_RANK_y', 'PTS_RANK_y',
       'PLUS_MINUS_RANK_y', 'NBA_FANTASY_PTS_RANK_y', 'DD2_RANK_y',
       'TD3_RANK_y', 'CFID_y', 'CFPARAMS_y'],
      dtype='object', length=131)

In [ ]:
frames[1].update

In [307]:
len(frames)

25

In [322]:
clutch_data[2]["PLAYER_NAME"] + " " + "1998-90"

0              A.C. Green 1998-90
1             Aaron McKie 1998-90
2          Aaron Williams 1998-90
3              Adam Keefe 1998-90
4            Adonal Foyle 1998-90
                  ...
361        Walter McCarty 1998-90
362         Wesley Person 1998-90
363           Will Perdue 1998-90
364    William Cunningham 1998-90
365    Zydrunas Ilgauskas 1998-90
Name: PLAYER_NAME, Length: 366, dtype: object

In [324]:
start = 1996
end = 2021


clutch_data_by_season = []
counter = 0
for start_year in range(start, end):
    season = '{}-{}'.format(start_year, str(start_year + 1)[2:])
    print(season)
    clutch_data_by_season.append(clutch.LeagueDashPlayerClutch
                  (per_mode_detailed = 'PerMinute', 
                   season = 
                   season).get_data_frames()[0][['PLAYER_ID', 'PLAYER_NAME', 'MIN', 'GP', 'W', 'L', 'PTS', 'REB', 'AST', 'FGM','FGA','FTA', 'PLUS_MINUS']])
    clutch_data_by_season[counter]['PLAYER_NAME'] =season + " " +clutch_data_by_season[counter]['PLAYER_NAME']
    counter += 1

1996-97
1997-98
1998-99
1999-00
2000-01
2001-02
2002-03
2003-04
2004-05
2005-06
2006-07
2007-08
2008-09
2009-10
2010-11
2011-12

ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

In [326]:
clutch_data[2].merge(clutch_data[1], how='outer', on = 'PLAYER_ID')

,PLAYER_ID,PLAYER_NAME_x,MIN_x,GP_x,W_x,L_x,PTS_x,REB_x,AST_x,FGM_x,...,GP_y,W_y,L_y,PTS_y,REB_y,AST_y,FGM_y,FGA_y,FTA_y,PLUS_MINUS_y
0,920,A.C. Green,31.431667,12.0,5.0,7.0,0.38,0.35,0.00,0.19,...,28.0,8.0,20.0,0.14,0.27,0.04,0.03,0.12,0.10,-0.17
1,243,Aaron McKie,66.863333,27.0,15.0,12.0,0.39,0.22,0.12,0.13,...,47.0,18.0,29.0,0.29,0.14,0.06,0.09,0.26,0.10,0.09
2,1425,Aaron Williams,5.741667,4.0,3.0,1.0,0.00,0.17,0.00,0.00,...,1.0,1.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,-8.57
3,228,Adam Keefe,25.995000,8.0,5.0,3.0,0.23,0.12,0.00,0.08,...,11.0,8.0,3.0,0.24,0.21,0.03,0.03,0.15,0.18,0.59
4,1502,Adonal Foyle,9.018333,4.0,1.0,3.0,0.33,0.33,0.00,0.11,...,3.0,1.0,2.0,0.00,0.13,0.00,0.00,0.00,0.00,1.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,8.0,4.0,0.19,0.24,0.10,0.10,0.24,0.00,-0.43
453,702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,35.0,22.0,13.0,0.40,0.12,0.04,0.08,0.24,0.23,0.34
454,416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,0.0,1.0,0.00,0.00,0.00,0.00,0.00,0.00,-12.37
455,1365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,2.0,3.0,0.00,0.14,0.00,0.00,0.14,0.00,-0.42
456,440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.0,1.0,6.0,0.14,0.07,0.00,0.07,0.07,0.00,0.14

In [ ]:
def merge_tables(t1, t2):
    t1.merge(t2, how='outer', on = 'PLAYER_ID')

In [ ]:
gamelog_bron_all = playergamelog.PlayerGameLog(player_id='2544', season = SeasonAll.all)

df_bron_games_all = gamelog_bron_all.get_data_frames()[0]


lebron_std = df_bron_games_all.std()

In [329]:
from nba_api.stats.endpoints import alltimeleadersgrids

In [331]:
leaderboard = alltimeleadersgrids.AllTimeLeadersGrids()

In [335]:
leaderboard.get_data_frames()[0]

   PLAYER_ID          PLAYER_NAME    GP  GP_RANK
0        305        Robert Parish  1611        1
1      76003  Kareem Abdul-Jabbar  1560        2
2       1713         Vince Carter  1541        3
3       1717        Dirk Nowitzki  1522        4
4        304        John Stockton  1504        5
5        252          Karl Malone  1476        6
6        708        Kevin Garnett  1462        7
7        788         Kevin Willis  1424        8
8       1891          Jason Terry  1410        9
9       1495           Tim Duncan  1392       10

In [337]:
from nba_api.stats.endpoints import cumestatsplayer

In [338]:
cumestatsplayer.CumeStatsPlayer()

TypeError: __init__() missing 2 required positional arguments: 'player_id' and 'game_ids'

In [339]:
pstats = playerstats.LeagueDashPlayerStats(season = '2018-19')

In [343]:
pstats.get_data_frames()[0]

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,MIN,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS
0,203932,Aaron Gordon,1610612753,ORL,23.0,78,40,38,0.513,2632.533333,...,471,439,39,52,91,43,34,38,5,"203932,1610612753"
1,1628988,Aaron Holiday,1610612754,IND,22.0,50,31,19,0.620,645.830000,...,218,210,283,302,97,324,261,38,5,"1628988,1610612754"
2,1627846,Abdel Nader,1610612760,OKC,25.0,61,38,23,0.623,693.656667,...,172,203,351,324,464,344,261,38,5,"1627846,1610612760"
3,201143,Al Horford,1610612738,BOS,33.0,68,41,27,0.603,1972.683333,...,353,343,154,97,37,64,70,16,5,"201143,1610612738"
4,202329,Al-Farouq Aminu,1610612757,POR,28.0,81,52,29,0.642,2291.698333,...,353,382,128,133,17,95,60,38,5,"202329,1610612757"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,203897,Zach LaVine,1610612741,CHI,24.0,63,16,47,0.254,2170.855000,...,526,372,40,30,512,54,159,38,5,"203897,1610612741"
526,1629155,Zach Lofton,1610612765,DET,26.0,1,1,0,1.000,3.750000,...,1,1,513,521,226,523,261,38,5,"1629155,1610612765"
527,2585,Zaza Pachulia,1610612765,DET,35.0,68,35,33,0.515,878.165000,...,262,400,134,316,424,281,261,38,5,"2585,1610612765"
528,1629015,Zhaire Smith,1610612755,PHI,20.0,6,2,4,0.333,110.616667,...,91,62,464,447,183,456,261,38,5,"1629015,1610612755"
529,1627753,Zhou Qi,1610612745,HOU,23.0,1,0,1,0.000,0.955000,...,1,1,513,514,239,523,261,38,5,"1627753,1610612745"

In [347]:
start = 1996
end = 2021


player_stats = []
counter = 0
for start_year in range(start, end):
    season = '{}-{}'.format(start_year, str(start_year + 1)[2:])
    print(season)
    player_stats.append(playerstats.LeagueDashPlayerStats
                  (per_mode_detailed = 'PerMinute', 
                   season = 
                   season).get_data_frames()[0][['PLAYER_ID', 'PLAYER_NAME', 'MIN', 'GP', 'W', 'L', 'PTS', 'REB', 'AST', 'FGM','FGA','FTA', 'PLUS_MINUS']])
    
  #  clutch_data_by_season[counter]['PLAYER_NAME'] =season + " " +clutch_data_by_season[counter]['PLAYER_NAME']
  #  counter += 1

1996-97

ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

In [351]:
from nba_api.stats.endpoints import playerdashboardbyclutch as pdc

In [369]:
clutch_df_pdc = pdc.PlayerDashboardByClutch(player_id = '2544', 
                                            measure_type_detailed='Base', 
                                            per_mode_detailed = 'Per36', 
                                            season = '2019-20',
                                            plus_minus = 'Y' ).get_data_frames()

In [372]:
clutch_df_pdc[0].columns

Index(['GROUP_SET', 'GROUP_VALUE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM',
       'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT',
       'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD',
       'PTS', 'PLUS_MINUS', 'CFID', 'CFPARAMS'],
      dtype='object')